[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 10
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'testnet'
rpc_addr = 'http://localhost:27001'
grpc_addr = 'http://localhost:26001'
event_source = { mode = 'push', url = 'ws://localhost:27001/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0, denom = 'uatom' }
gas_multiplier = 1.5
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"

[[chains]]
id = 'two'
rpc_addr = 'http://localhost:27011'
grpc_addr = 'http://localhost:26011'
event_source = { mode = 'push', url = 'ws://localhost:27011/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0, denom = 'uatom' }
gas_multiplier = 1.5
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"
