---
- name: Clone ubuntu runner template
  community.general.proxmox_kvm:
    api_host: cosmos-kvm1.polypore.xyz
    api_user: ciuser@pve
    node: cosmos-kvm4
    pool: ci
    clone: git-runner-ubuntu-2404
    name: cosmos-git-runner-ubuntu-unset
    vmid: 9351
    # newid: 600
    storage: local
    format: qcow2
    timeout: 500
    full: true
  register: proxmox_info
- name: Store vmid
  set_fact:
    vmid: "{{ proxmox_info.data.vmid }}"
- name: Grow existing disk
  community.general.proxmox_disk:
    api_host: cosmos-kvm1.polypore.xyz
    api_user: ciuser@pve
    vmid: "{{ vmid }}"
    disk: virtio0
    size: 100G
    state: resized

- name: Configure runner VM
  community.general.proxmox_kvm:
    api_host: cosmos-kvm1.polypore.xyz
    api_user: ciuser@pve
    node: cosmos-kvm4
    pool: ci
    vmid: "{{ vmid }}"
    cores: 8
    name: cosmos-git-runner-ubuntu-{{ vmid }}
    memory: 16384
    update: true

- name: Start runner VM
  community.general.proxmox_kvm:
    api_host: cosmos-kvm1.polypore.xyz
    api_user: ciuser@pve
    node: cosmos-kvm4
    pool: ci
    vmid: "{{ vmid }}"
    state: started
