---
- name: Clone ubuntu runner template
  community.general.proxmox_kvm:
    api_host: cosmos-kvm1.polypore.xyz
    api_user: ciuser@pve
    node: cosmos-kvm4
    pool: ci
    clone: git-runner-ubuntu-2404
    name: cosmos-git-runner-ubuntu-600
    vmid: 9351
    newid: 600
    storage: local
    format: qcow2
    timeout: 500
    full: true

- name: Grow existing disk
  community.general.proxmox_disk:
    api_host: cosmos-kvm1.polypore.xyz
    api_user: ciuser@pve
    vmid: 600
    disk: virtio
    size: 100G
    state: resized

- name: Configure and Start runner VM
  community.general.proxmox_kvm:
    api_host: cosmos-kvm1.polypore.xyz
    api_user: ciuser@pve
    node: cosmos-kvm4
    pool: ci
    name: cosmos-git-runner-ubuntu-600
    vmid: 600
    cores: 8
    memory: 16384
    virtio:
      virtio0: 'local:500'
    state: started