gaia:
  name: gaia
  type: cosmos
  bin: gaiad
  bech32-prefix: cosmos
  denom: uatom
  gas-prices: 0.005uatom
  gas-adjustment: 2.0
  trusting-period: 504h
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/gaia
      uid-gid: 1025:1025
  no-host-mount: false

stride:
  name: stride
  type: cosmos
  bin: strided
  bech32-prefix: stride
  denom: ustrd
  gas-prices: 0.01ustrd
  gas-adjustment: 1.3
  trusting-period: "336h"
  images:
    - repository: ghcr.io/strangelove-ventures/heighliner/stride
      uid-gid: 1025:1025
  no-host-mount: false
