[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'consumera'
rpc_addr = 'http://localhost:27101'
grpc_addr = 'http://localhost:26101'
event_source = { mode = 'push', url = 'ws://localhost:27101/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'consumer'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.1
max_gas = 10000000
clock_drift = '10s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'consumerb'
rpc_addr = 'http://localhost:57101'
grpc_addr = 'http://localhost:56101'
event_source = { mode = 'push', url = 'ws://localhost:57101/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'consumer'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.1
max_gas = 10000000
clock_drift = '10s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'consumerc'
rpc_addr = 'http://localhost:27301'
grpc_addr = 'http://localhost:26301'
event_source = { mode = 'push', url = 'ws://localhost:27301/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0, denom = 'ucon' }
gas_multiplier = 1.1
max_gas = 10000000
clock_drift = '10s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'consumerf'
rpc_addr = 'http://localhost:27401'
grpc_addr = 'http://localhost:26401'
event_source = { mode = 'push', url = 'ws://localhost:27401/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0, denom = 'ucon' }
gas_multiplier = 1.1
max_gas = 10000000
clock_drift = '10s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'ica-chain'
rpc_addr = 'http://localhost:37011'
grpc_addr = 'http://localhost:36011'
event_source = { mode = 'push', url = 'ws://localhost:37011/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.6
max_gas = 10000000
clock_drift = '10s'
trusting_period = '600s'
trust_threshold = '2/3'
client_refresh_rate = '1/5'
type = "CosmosSdk"

[[chains]]
id = '_CHAIN_ID_'
rpc_addr = 'http://localhost:27001'
grpc_addr = 'http://localhost:26001'
event_source = { mode = 'push', url = 'ws://localhost:27001/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.6
max_gas = 10000000
clock_drift = '10s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"
dynamic_gas_price = { enabled=true, multiplier = 1.5, max = 0.2 } 
