[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'v310-one'
rpc_addr = 'http://localhost:31121'
grpc_addr = 'http://localhost:31111'
event_source = { mode = 'push', url = 'ws://localhost:31121/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'v310-two'
rpc_addr = 'http://localhost:31221'
grpc_addr = 'http://localhost:31211'
event_source = { mode = 'push', url = 'ws://localhost:31221/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'v320-one'
rpc_addr = 'http://localhost:32121'
grpc_addr = 'http://localhost:32111'
event_source = { mode = 'push', url = 'ws://localhost:32121/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'v320-two'
rpc_addr = 'http://localhost:32221'
grpc_addr = 'http://localhost:32211'
event_source = { mode = 'push', url = 'ws://localhost:32221/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'v330-one'
rpc_addr = 'http://localhost:33121'
grpc_addr = 'http://localhost:33111'
event_source = { mode = 'push', url = 'ws://localhost:33121/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'v330-two'
rpc_addr = 'http://localhost:33221'
grpc_addr = 'http://localhost:33211'
event_source = { mode = 'push', url = 'ws://localhost:33221/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'v400-one'
rpc_addr = 'http://localhost:40121'
grpc_addr = 'http://localhost:40111'
event_source = { mode = 'push', url = 'ws://localhost:40121/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'consumer'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'v400-two'
rpc_addr = 'http://localhost:40221'
grpc_addr = 'http://localhost:40211'
event_source = { mode = 'push', url = 'ws://localhost:40221/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'consumer'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'neutron-test'
rpc_addr = 'http://localhost:31321'
grpc_addr = 'http://localhost:31311'
event_source = { mode = 'push', url = 'ws://localhost:31321/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'neutron'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.02, denom = 'untrn' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'stride-test'
rpc_addr = 'http://localhost:32321'
grpc_addr = 'http://localhost:32311'
event_source = { mode = 'push', url = 'ws://localhost:32321/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'stride'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ustrd' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'testnet'
rpc_addr = 'http://localhost:27001'
grpc_addr = 'http://localhost:26001'
event_source = { mode = 'push', url = 'ws://localhost:27001/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.5
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"

[[chains]]
id = 'pfm1'
rpc_addr = 'http://localhost:27011'
grpc_addr = 'http://localhost:26011'
event_source = { mode = 'push', url = 'ws://localhost:27011/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"

[[chains]]
id = 'pfm2'
rpc_addr = 'http://localhost:27012'
grpc_addr = 'http://localhost:26012'
event_source = { mode = 'push', url = 'ws://localhost:27012/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"

[[chains]]
id = 'pfm3'
rpc_addr = 'http://localhost:27013'
grpc_addr = 'http://localhost:26013'
event_source = { mode = 'push', url = 'ws://localhost:27013/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"