[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'one-v120'
rpc_addr = 'http://localhost:27101'
grpc_addr = 'http://localhost:26101'
event_source = { mode = 'push', url = 'ws://localhost:27101/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'two-v200'
rpc_addr = 'http://localhost:27201'
grpc_addr = 'http://localhost:26201'
event_source = { mode = 'push', url = 'ws://localhost:27201/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'three-v310'
rpc_addr = 'http://localhost:27301'
grpc_addr = 'http://localhost:26301'
event_source = { mode = 'push', url = 'ws://localhost:27301/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'four-v330'
rpc_addr = 'http://localhost:27401'
grpc_addr = 'http://localhost:26401'
event_source = { mode = 'push', url = 'ws://localhost:27401/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'five'
rpc_addr = 'http://localhost:27501'
grpc_addr = 'http://localhost:26501'
event_source = { mode = 'push', url = 'ws://localhost:27501/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'stride'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ustrd' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'six-v310'
rpc_addr = 'http://localhost:27601'
grpc_addr = 'http://localhost:26601'
event_source = { mode = 'push', url = 'ws://localhost:27601/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'seven-v320'
rpc_addr = 'http://localhost:27701'
grpc_addr = 'http://localhost:26701'
event_source = { mode = 'push', url = 'ws://localhost:27701/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'eight-v330'
rpc_addr = 'http://localhost:27801'
grpc_addr = 'http://localhost:26801'
event_source = { mode = 'push', url = 'ws://localhost:27801/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'nine-v400'
rpc_addr = 'http://localhost:27901'
grpc_addr = 'http://localhost:26901'
event_source = { mode = 'push', url = 'ws://localhost:27901/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'consumer'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'ten-v400'
rpc_addr = 'http://localhost:47901'
grpc_addr = 'http://localhost:46901'
event_source = { mode = 'push', url = 'ws://localhost:47901/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'consumer'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"

[[chains]]
id = 'testnet'
rpc_addr = 'http://localhost:27001'
grpc_addr = 'http://localhost:26001'
event_source = { mode = 'push', url = 'ws://localhost:27001/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.5
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"

[[chains]]
id = 'pfm1'
rpc_addr = 'http://localhost:27011'
grpc_addr = 'http://localhost:26011'
event_source = { mode = 'push', url = 'ws://localhost:27011/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"

[[chains]]
id = 'pfm2'
rpc_addr = 'http://localhost:27012'
grpc_addr = 'http://localhost:26012'
event_source = { mode = 'push', url = 'ws://localhost:27012/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"

[[chains]]
id = 'pfm3'
rpc_addr = 'http://localhost:27013'
grpc_addr = 'http://localhost:26013'
event_source = { mode = 'push', url = 'ws://localhost:27013/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"