---
- hosts: localhost
  roles:
  - role: provision-vm-runner
    become: false
    api_host: cosmos-kvm1.polypore.xyz
    api_user: ciuser@pve
    vm_node: cosmos-kvm4
    vm_name_prefix: cosmos-git-runner-ubuntu
    resource_pool: ci
    template_clone: git-runner-ubuntu-2404
    template_id: 9351
    memory: 65536
    cpu_cores: 8
    disk_size: 100G
