[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001


[[chains]]
id = 'v330-one'
rpc_addr = 'http://localhost:33021'
grpc_addr = 'http://localhost:33011'
event_source = { mode = 'push', url = 'ws://localhost:33021/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.0025, denom = 'ucon' }
gas_multiplier = 1.2
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
ccv_consumer_chain = true
type = "CosmosSdk"


[[chains]]
id = 'testnet'
rpc_addr = 'http://localhost:27001'
grpc_addr = 'http://localhost:26001'
event_source = { mode = 'push', url = 'ws://localhost:27001/websocket', batch_delay = '500ms' }
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'wallet'
store_prefix = 'ibc'
gas_price = { price = 0.005, denom = 'uatom' }
gas_multiplier = 1.5
max_gas = 10000000
clock_drift = '10s'
trusting_period = '5days'
trust_threshold = { numerator = '1', denominator = '3' }
type = "CosmosSdk"
