---

name: Join Release Testnet
on:
  push:
  workflow_dispatch:
#   schedule:
    # At 15:30 on Monday.
    # - cron: '30 15 * * 1'
concurrency:
  group: self-hosted-runners
jobs:
  test-public-testnet:
    runs-on: self-hosted-ubuntu-22.04
    steps:
      # Get system info
      - run: ifconfig
      - run: lscpu
      - run: df -h
      - run: free -m
      - run: uname -a
      - run: lsb_release -a
      - run: echo "GitHub branch is ${{ github.ref }}"
      - run: whoami
      - run: pwd
      # - name: mkdir ~/artifact
      #   run: mkdir ~/artifact
      - name: Update Apt
        run: |
          sudo apt update
          sudo apt dist-upgrade -y
      - name: Install required packages
        run: |
          sudo apt -y install python-is-python3 python3-distutils screen tmux curl jq wget python3-venv python3-pip
      - name: Check out repository code
        uses: actions/checkout@v3
    #   - name: Init Python venv
    #     run: python -m venv ~/env
    #   - name: Install dependencies
    #     run: |
    #       source ~/env/bin/activate
    #       python -m pip install --upgrade pip
    #       python -m pip install toml toml-cli ansible
    #   - name: Configure ansible.cfg
    #     run: |
    #       source ~/env/bin/activate
    #       echo "transport = local" >> ansible.cfg
    #   - name: Install ansible-galaxy requirements
    #     run: |
    #       source ~/env/bin/activate
    #       ansible-galaxy install -r requirements.yml
      - name: Set up release testnet home folder
        run: |
          tests/setup_release_testnet.sh
      - name: Start node
        run: |
          export PATH="$PATH:/home/runner/go/bin"
          touch /home/runner/gaia.log
          tmux new-session -d -s gaia '/home/runner/go/bin/gaiad start --home /home/runner/.release |& tee -a /home/runner/gaia.log'
          sleep 60
          tail -n 100 /home/runner/gaia.log
      - name: Check blocks are being produced
        run: |
          height=$(curl -s http://rpc.state-sync-01.theta-testnet.polypore.xyz:26657/block | jq -r '.result.block.header.height')
          echo "Waiting for block $[ $height + 100 ]..."
          tests/test_block_production.sh 127.0.0.1 26657 100
