---

    name: Test ARM Architecture
    on:
      workflow_dispatch:
        inputs:
          testnet-version:
            description: 'Testnet version to test'
            required: true
            type: string
            default: v27.3.0-rc0
          mainnet-version:
            description: 'Mainnet version to test'
            required: true
            type: string
            default: v27.2.0
          # from_version:
          #   description: 'Gaia version to upgrade from'
          #   required: true
          #   type: string
          #   default: v26.0.0
          # to_version:
          #   description: 'Gaia version to upgrade to'
          #   required: true
          #   type: string
          #   default: v27.3.0-rc0
          # upgrade_name:
          #   description: 'Name of the upgrade'
          #   required: false
          #   type: string
          #   default: v27.3.0
      push:
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    env:
      GO_VERSION: 1.25.7
      # All chain variables
      COMMIT_TIMEOUT: 2
      # Consumer chain variables
      RECIPIENT: cosmos1r5v5srda7xfth3hn2s26txvrcrntldjumt8mhl
      PROVIDER_ICS: v6.4.0
      TOPN: 0
      # Relayer variables
      RELAYER: hermes
      HERMES_VERSION: v1.13.3
      RLY_VERSION: "2.5.0"
    jobs:
      # set-versions:
      #   env:
      #     START: ${{ github.event_name == 'push' && 'v26.0.0' || inputs.from_version }}
      #     TARGET: ${{ github.event_name == 'push' && 'v27.3.0-rc0' || inputs.to_version }}
      #     NAME: ${{ github.event_name == 'push' && 'v27.3.0' || inputs.upgrade_name }}
      #   runs-on: ubuntu-24.04-arm
      #   steps:
      #     - name: Debug env vars
      #       run: |
      #         echo "START: $START"
      #         echo "TARGET: $TARGET"
      #         echo "NAME: $NAME"
      #         ldd --version
      #     - name: Check out repository code
      #       uses: actions/checkout@v6
      #     - name: Set up Python
      #       uses: actions/setup-python@v6
      #       with:
      #         python-version: '3.11'
      #     - name: Install dependencies
      #       run: |
      #         python -m pip install --upgrade pip
      #         python -m pip install requests
      #     - name: Set starting version
      #       id: start
      #       run: |
      #         echo "version=$START" >> $GITHUB_OUTPUT
      #     - name: Set target version
      #       id: target
      #       run: |
      #         echo "version=$TARGET" >> $GITHUB_OUTPUT
      #     - name: Set upgrade name
      #       id: upgrade
      #       run: |
      #         echo "name=$NAME" >> $GITHUB_OUTPUT
      #     - name: Set binary source
      #       id: binary
      #       run: |
      #         if [[ "${TARGET:0:1}" != "v" ]]; then
      #           echo "source=BUILD" >> $GITHUB_OUTPUT
      #         else
      #           echo "source=DOWNLOAD" >> $GITHUB_OUTPUT
      #         fi
              
      #   outputs:
      #    start_version: ${{ steps.start.outputs.version }}
      #    target_version: ${{ steps.target.outputs.version }}
      #    upgrade_name: ${{ steps.upgrade.outputs.name }}
      #    binary_source: ${{ steps.binary.outputs.source }}

      Test-chain-start:
        runs-on: ubuntu-24.04-arm
        # needs: set-versions
        strategy:
          # matrix:
          #   start_version: [ "${{ needs.set-versions.outputs.start_version }}" ]
          #   target_version: [ "${{ needs.set-versions.outputs.target_version }}" ]
          #   upgrade_name: [ "${{ needs.set-versions.outputs.upgrade_name }}" ]
          #   cv_version: [v1.7.1]
          #   upgrade_mechanism: [cv_auto, cv_manual]
          #   enable_cosmovisor: [false, true]
          #   exclude:
          #     - target_version: main
          #       upgrade_mechanism: cv_auto
          #     - enable_cosmovisor: false
          #       upgrade_mechanism: cv_auto
          fail-fast: false
        env:
          # COSMOVISOR: ${{ matrix.enable_cosmovisor }}
          # COSMOVISOR_VERSION: ${{ matrix.cv_version }}
          # UPGRADE_MECHANISM: ${{ matrix.upgrade_mechanism }}
          # BINARY_SOURCE: ${{ needs.set-versions.outputs.binary_source }}
          BINARY_SOURCE: DOWNLOAD
          GO_VERSION: 1.25.7
          GAIA_VERSION: ${{ github.event_name == 'push' && 'v27.3.0-rc0' || inputs.gaia-version }}
        steps:
          - name: Update PATH
            run: |
              mkdir -p $HOME/go/bin
              echo "$HOME/go/bin" >> $GITHUB_PATH
              echo "$HOME/.hermes" >> $GITHUB_PATH
              echo "$HOME/.relayer" >> $GITHUB_PATH
          - name: Bypass the grub-efi-amd64-signed package
            run: sudo apt-mark hold grub-efi-arm64-signed
          - name: Check out repository code
            uses: actions/checkout@v6
          - name: Set up Python
            uses: actions/setup-python@v6
            with:
              python-version: '3.11'
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install toml-cli
          - name: Start chain
            run: |
              export CHAIN_BINARY_URL=https://github.com/cosmos/gaia/releases/download/$GAIA_VERSION/gaiad-$GAIA_VERSION-linux-arm64  
              source scripts/vars.sh
              scripts/setup.sh
              ./$START_SCRIPT
              sleep $(($COMMIT_TIMEOUT*2))
              tail -n 100 $whale_log
              scripts/wait_for_block.sh 3
              
          - name: _Blocks produced
            run: |
              source scripts/vars.sh
              tests/test_block_production.sh 127.0.0.1 ${rpc_prefix}$COUNT_WIDTH 5

          - name: _Transactions verified> bank send, delegate, and withdraw rewards
            run: |
              source scripts/vars.sh
              tests/test_tx.sh

                  
          - name: _Transactions verified> bank send, delegate, and withdraw rewards
            run: |
              source scripts/vars.sh
              tests/test_tx.sh

          - name: _API endpoints check
            run: |
              source scripts/vars.sh
              tests/test_endpoints_api.sh localhost ${api_prefix}$COUNT_WIDTH

          - name: _RPC endpoints check
            run: |
              source scripts/vars.sh
              tests/test_endpoints_rpc.sh localhost ${rpc_prefix}$COUNT_WIDTH
  
          - name: _Blocks produced
            run: |
              source scripts/vars.sh
              tests/test_block_production.sh 127.0.0.1 ${rpc_prefix}$COUNT_WIDTH 5


      Test-testnet-snapshot:
        runs-on: ubuntu-24.04-arm
        strategy:
          fail-fast: false
        env:
          BINARY_SOURCE: DOWNLOAD
          GO_VERSION: 1.25.7
          GAIA_VERSION: ${{ github.event_name == 'push' && 'v27.3.0-rc0' || inputs.gaia-version }}
        steps:
          - name: Update PATH
            run: |
              mkdir -p $HOME/go/bin
              echo "$HOME/go/bin" >> $GITHUB_PATH
          - name: Bypass the grub-efi-arm64-signed package
            run: sudo apt-mark hold grub-efi-arm64-signed
          - name: Check out repository code
            uses: actions/checkout@v6
          - name: Set up Python
            uses: actions/setup-python@v6
            with:
              python-version: '3.11'
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install toml-cli

          - name: Start chain
            env:
              NODE_HOME: /home/runner/.gaia
              CHAIN_BINARY: ./gaiad
              GAS_PRICE: 0.005uatom
            run: |
              echo "> Downloading Gaia"
              wget https://github.com/cosmos/gaia/releases/download/$GAIA_VERSION/gaiad-$GAIA_VERSION-linux-arm64 -O $CHAIN_BINARY
              chmod +x $CHAIN_BINARY
              echo "> Initializing node @ $NODE_HOME"
              $CHAIN_BINARY init provider-node --home $NODE_HOME
              sed -i -e "/minimum-gas-prices =/ s^= .*^= \"$GAS_PRICE\"^" $NODE_HOME/config/app.toml
              echo "> Downloading genesis file"
              wget https://github.com/cosmos/testnets/raw/refs/heads/master/provider/provider-genesis.json -O $NODE_HOME/config/genesis.json
              echo "> Setting up seeds"
              toml set --toml-path $NODE_HOME/config/config.toml p2p.seeds "08ec17e86dac67b9da70deb20177655495a55407@provider-seed-01.hub-testnet.polypore.xyz:26656,4ea6e56300a2f37b90e58de5ee27d1c9065cf871@provider-seed-02.hub-testnet.polypore.xyz:26656"
              pwd
              echo "> Downloading and extracting snapshot"
              pushd $NODE_HOME
              wget https://snapshots.polypore.xyz/provider/latest.tar.gz
              tar -xzf latest.tar.gz
              pwd
              popd
              pwd
              echo "> Starting node session."
              tmux new-session -d -s arm-test "$CHAIN_BINARY start --home $NODE_HOME 2>&1 | tee gaia.log"
              sleep 10s
              tail -n 100 gaia.log

          - name: Wait until syncing flag is set to false
            run: |
              while true; do
                syncing=$(curl -s localhost:26657/status | jq -r '.result.sync_info.catching_up')
                if [ "$syncing" == "false" ]; then
                  echo "Node has finished syncing!"
                  break
                else
                  echo "Node is still syncing... waiting 1m before checking again."
                  tail -n 20 gaia.log
                  sleep 1m
                fi
              done

          - name: Print log
            run: |
              tail -n 100 gaia.log

      Test-mainnet-snapshot:
        runs-on: ubuntu-24.04-arm
        strategy:
          fail-fast: false
        env:
          BINARY_SOURCE: DOWNLOAD
          GO_VERSION: 1.25.7
          GAIA_VERSION: ${{ github.event_name == 'push' && 'v27.2.0' || inputs.gaia-version }}
        steps:
          - name: Update PATH
            run: |
              mkdir -p $HOME/go/bin
              echo "$HOME/go/bin" >> $GITHUB_PATH
          - name: Bypass the grub-efi-arm64-signed package
            run: sudo apt-mark hold grub-efi-arm64-signed
          - name: Check out repository code
            uses: actions/checkout@v6
          - name: Set up Python
            uses: actions/setup-python@v6
            with:
              python-version: '3.11'
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install toml-cli
              sudo apt install aria2 -y

          - name: Start chain
            env:
              NODE_HOME: /home/runner/.gaia
              CHAIN_BINARY: ./gaiad
              GAS_PRICE: 0.005uatom
            run: |
              echo "> Downloading Gaia"
              wget https://github.com/cosmos/gaia/releases/download/$GAIA_VERSION/gaiad-$GAIA_VERSION-linux-arm64 -O $CHAIN_BINARY
              chmod +x $CHAIN_BINARY
              echo "> Initializing node @ $NODE_HOME"
              $CHAIN_BINARY init provider-node --home $NODE_HOME
              sed -i -e "/minimum-gas-prices =/ s^= .*^= \"$GAS_PRICE\"^" $NODE_HOME/config/app.toml
              echo "> Downloading genesis file"
              wget https://snapshots.polkachu.com/genesis/cosmos/genesis.json -O $NODE_HOME/config/genesis.json
              echo "> Setting up seeds"
              toml set --toml-path $NODE_HOME/config/config.toml p2p.seeds "327fb4151de9f78f29ff10714085e347a4e3c836@rpc.cosmos.nodestake.org:666"
              echo "> Downloading and extracting snapshot"
              aria2c -x 8 -s 8 https://snapshots.polypore.xyz/cosmoshub-4/latest.tar.lz4
              lz4 -c -d latest.tar.lz4  | tar -x -C $NODE_HOME
              echo "> Starting node session."
              tmux new-session -d -s arm-test "$CHAIN_BINARY start --home $NODE_HOME 2>&1 | tee gaia.log"
              sleep 10s
              tail -n 100 gaia.log

          - name: Wait until syncing flag is set to false
            run: |
              while true; do
                syncing=$(curl -s localhost:26657/status | jq -r '.result.sync_info.catching_up')
                if [ "$syncing" == "false" ]; then
                  echo "Node has finished syncing!"
                  break
                else
                  echo "Node is still syncing... waiting 1m before checking again."
                  tail -n 20 gaia.log
                  sleep 1m
                fi
              done

          - name: Print log
            run: |
              tail -n 100 gaia.log

      # Test-testnet-state-sync:
      #   runs-on: ubuntu-24.04-arm
      #   strategy:
      #     fail-fast: false
      #   env:
      #     BINARY_SOURCE: DOWNLOAD
      #     GO_VERSION: 1.25.7
      #     GAIA_VERSION: ${{ github.event_name == 'push' && 'v27.3.0-rc0' || inputs.gaia-version }}
      #   steps:
      #     - name: Update PATH
      #       run: |
      #         mkdir -p $HOME/go/bin
      #         echo "$HOME/go/bin" >> $GITHUB_PATH
      #     - name: Bypass the grub-efi-arm64-signed package
      #       run: sudo apt-mark hold grub-efi-arm64-signed
      #     - name: Check out repository code
      #       uses: actions/checkout@v6
      #     - name: Set up Python
      #       uses: actions/setup-python@v6
      #       with:
      #         python-version: '3.11'
      #     - name: Install dependencies
      #       run: |
      #         python -m pip install --upgrade pip
      #         python -m pip install toml-cli

      #     - name: Start chain
      #       env:
      #         NODE_HOME: /home/runner/.gaia
      #         CHAIN_BINARY: ./gaiad
      #         GAS_PRICE: 0.005uatom
      #         STATE_SYNC_RPC_1: https://rpc.provider-state-sync-01.hub-testnet.polypore.xyz:443
      #         STATE_SYNC_RPC_2: https://rpc.provider-state-sync-02.hub-testnet.polypore.xyz:443
      #       run: |
      #         echo "> Downloading Gaia"
      #         wget https://github.com/cosmos/gaia/releases/download/$GAIA_VERSION/gaiad-$GAIA_VERSION-linux-arm64 -O $CHAIN_BINARY
      #         chmod +x $CHAIN_BINARY
      #         echo "> Initializing node @ $NODE_HOME"
      #         $CHAIN_BINARY init provider-node --home $NODE_HOME
      #         sed -i -e "/minimum-gas-prices =/ s^= .*^= \"$GAS_PRICE\"^" $NODE_HOME/config/app.toml
      #         echo "> Downloading genesis file"
      #         wget https://github.com/cosmos/testnets/raw/refs/heads/master/provider/provider-genesis.json -O $NODE_HOME/config/genesis.json
      #         echo "> Setting up seeds"
      #         toml set --toml-path $NODE_HOME/config/config.toml p2p.seeds "08ec17e86dac67b9da70deb20177655495a55407@provider-seed-01.hub-testnet.polypore.xyz:26656,4ea6e56300a2f37b90e58de5ee27d1c9065cf871@provider-seed-02.hub-testnet.polypore.xyz:26656"
      #         echo "> Setting up state sync"
      #         current_height=$(curl -s $STATE_SYNC_RPC_1/block | jq -r '.result.block.header.height')
      #         echo "> Current block height: $current_height"
      #         trust_height=$[$current_height-1000]
      #         trust_block=$(curl -s $STATE_SYNC_RPC_1/block\?height\=$trust_height)
      #         trust_hash=$(echo $trust_block | jq -r '.result.block_id.hash')
      #         toml set --toml-path $NODE_HOME/config/config.toml statesync.enable true
      #         toml set --toml-path $NODE_HOME/config/config.toml statesync.trust_period "8h0m0s"
      #         toml set --toml-path $NODE_HOME/config/config.toml statesync.trust_height $trust_height
      #         toml set --toml-path $NODE_HOME/config/config.toml statesync.trust_hash $trust_hash
      #         toml set --toml-path $NODE_HOME/config/config.toml statesync.rpc_servers "$STATE_SYNC_RPC_1,$STATE_SYNC_RPC_2"
      #         echo "> Starting node session."
      #         tmux new-session -d -s arm-test "$CHAIN_BINARY start --home $NODE_HOME 2>&1 | tee gaia.log"
      #         sleep 10s
      #         tail -n 100 gaia.log
            
      #     - name: Wait until syncing flag is set to false
      #       run: |
      #         while true; do
      #           syncing=$(curl -s localhost:26657/status | jq -r '.result.sync_info.catching_up')
      #           if [ "$syncing" == "false" ]; then
      #             echo "Node has finished syncing!"
      #             break
      #           else
      #             echo "Node is still syncing... waiting 1m before checking again."
      #             sleep 1m
      #           fi
      #         done

      #     - name: Print log
      #       run: |
      #         tail -n 100 gaia.log

