---

name: Test Gaia Stateful Upgrade - v24
on:
  repository_dispatch:
    types: [new_main_build]
  workflow_dispatch:
    inputs:
      from_version:
        description: 'Gaia version to upgrade from'
        required: true
        type: string
        default: v23.3.0
      to_version:
        description: 'Gaia version to upgrade to'
        required: true
        default: main

  # schedule:
  #   # Once a day at 13:15
  #   - cron: '15 13 * * 1'
  push:
concurrency:
  group: self-hosted-runners
jobs:
  set-version-matrix:
    env:
      START: ${{ github.event_name == 'push' && 'v23.3.0' || inputs.from_version }}
      TARGET: ${{ github.event_name == 'push' && 'main' || inputs.to_version }}
    runs-on: ubuntu-22.04
    steps:
      # Get system info
      - run: ifconfig
      - run: arp -a
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: uname -a
      - run: lsb_release -a
      - run: echo "GitHub branch is ${{ github.ref }}"
      - run: whoami
      - run: pwd
      # Debug
      - name: Debug env vars
        run: |
          echo "START: $START"
          echo "TARGET: $TARGET"
      - name: Set starting version
        id: start
        run: |
          echo "version=$START" >> $GITHUB_OUTPUT
      - name: Set target version
        id: target
        run: |
          echo "version=$TARGET" >> $GITHUB_OUTPUT
    outputs:
      # upgrade_versions: ${{ steps.generate-upgrade.outputs.upgrade_versions }}
      gaia_version: ${{ steps.start.outputs.version }}
      upgrade_version: ${{ steps.target.outputs.version }}

  test-upgrade-mainnet:
    needs: set-version-matrix
    strategy:
      matrix:
        # ${{ fromJSON(needs.set-version-matrix.outputs.upgrade_versions) }}
        gaia_version: [ "${{ needs.set-version-matrix.outputs.gaia_version }}" ]
        upgrade_version: [ "${{ needs.set-version-matrix.outputs.upgrade_version }}" ]
      fail-fast: false
      #max-parallel: 3
    with:
      runs-on-os: cosmos-runner-set
      from_version: ${{ matrix.from_version }}
      gaia_version: ${{ matrix.gaia_version }}
      upgrade_version: ${{ matrix.upgrade_version }}
      env_name: major-upgrade-stateful-workflow
      archive_url: https://files.polypore.xyz/archived-state/latest_v23.tar.gz
    uses: ./.github/workflows/upgrade-gaia-v24-stateful-steps.yml

  # test-upgrade-release-testnet:
  #   needs: set-version-matrix
  #   strategy:
  #     matrix:
  #       ${{ fromJSON(needs.set-version-matrix.outputs.upgrade_versions) }}
  #     fail-fast: false
  #     #max-parallel: 3
  #   with:
  #     runs-on-os: cosmos-runner-set
  #     gaia_version: ${{ matrix.gaia_version }}
  #     upgrade_version: ${{ matrix.upgrade_version }}
  #     env_name: major-upgrade-theta-stateful-workflow
  #     archive_url: https://files.polypore.xyz/archived-state/theta-testnet/latest_v23.tar.gz
  #   uses: ./.github/workflows/upgrade-gaia-v24-stateful-steps.yml

  # test-upgrade-ics-testnet:
  #   needs: set-version-matrix
  #   strategy:
  #     matrix:
  #       ${{ fromJSON(needs.set-version-matrix.outputs.upgrade_versions) }}
  #     fail-fast: false
  #     #max-parallel: 3
  #   with:
  #     runs-on-os: cosmos-runner-set
  #     gaia_version: ${{ matrix.gaia_version }}
  #     upgrade_version: ${{ matrix.upgrade_version }}
  #     env_name: major-upgrade-ics-stateful-workflow
  #     archive_url: https://files.polypore.xyz/archived-state/ics-testnet-provider/latest_v23.tar.gz
  #   uses: ./.github/workflows/upgrade-gaia-v24-stateful-steps.yml
