---

name: Test Gaia Stateful Upgrade - v24
on:
  repository_dispatch:
    types: [new_main_build]
  workflow_dispatch:
    inputs:
      from_version:
        description: 'Gaia version to upgrade from'
        required: true
        type: string
        default: v23.3.0
      to_version:
        description: 'Gaia version to upgrade to'
        required: true
        default: v24.0.0-rc0
      archive_url:
        description: 'URL for archive file'
        required: true
        # default: 'https://files.polypore.xyz/archived-state/latest_v23.tar.gz'
        # default: 'https://files.polypore.xyz/archived-state/v23.3.0_25706750-stateful-upgrade.tar.gz'
        default: 'https://files.polypore.xyz/archived-state/v23.3.0_25740800-stateful-upgrade.tar.gz'

  # schedule:
  #   # Once a day at 13:15
  #   - cron: '15 13 * * 1'
  # push:
concurrency:
  group: self-hosted-runners
jobs:
  set-version-matrix:
    env:
      START: ${{ github.event_name == 'push' && 'v23.3.0' || inputs.from_version }}
      TARGET: ${{ github.event_name == 'push' && 'v24.0.0-rc0' || inputs.to_version }}
      # ARCHIVE_URL: ${{ github.event_name == 'push' && 'https://files.polypore.xyz/archived-state/latest_v23.tar.gz' || inputs.archive_url }}
      # ARCHIVE_URL: ${{ github.event_name == 'push' && 'https://files.polypore.xyz/archived-state/v23.3.0_25706750-stateful-upgrade.tar.gz' || inputs.archive_url }}
      ARCHIVE_URL: ${{ github.event_name == 'push' && 'https://files.polypore.xyz/archived-state/v23.3.0_25740800-stateful-upgrade.tar.gz' || inputs.archive_url }}
    runs-on: ubuntu-22.04
    steps:
      # Get system info
      - run: ifconfig
      - run: arp -a
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: uname -a
      - run: lsb_release -a
      - run: echo "GitHub branch is ${{ github.ref }}"
      - run: whoami
      - run: pwd
      # Debug
      - name: Debug env vars
        run: |
          echo "START: $START"
          echo "TARGET: $TARGET"
          echo "ARCHIVE_URL: $ARCHIVE_URL"
      - name: Set starting version
        id: start
        run: |
          echo "version=$START" >> $GITHUB_OUTPUT
      - name: Set target version
        id: target
        run: |
          echo "version=$TARGET" >> $GITHUB_OUTPUT
      - name: Set archive URL
        id: archive
        run: |
          echo "url=$ARCHIVE_URL" >> $GITHUB_OUTPUT
    outputs:
      gaia_version: ${{ steps.start.outputs.version }}
      upgrade_version: ${{ steps.target.outputs.version }}
      archive_url: ${{ steps.archive.outputs.url }}

  test-upgrade-mainnet:
    needs: set-version-matrix
    strategy:
      matrix:
        # ${{ fromJSON(needs.set-version-matrix.outputs.upgrade_versions) }}
        gaia_version: [ "${{ needs.set-version-matrix.outputs.gaia_version }}" ]
        upgrade_version: [ "${{ needs.set-version-matrix.outputs.upgrade_version }}" ]
        archive_url: [ "${{ needs.set-version-matrix.outputs.archive_url }}" ]
      fail-fast: false
      #max-parallel: 3
    with:
      runs-on-os: cosmos-runner-set
      gaia_version: ${{ matrix.gaia_version }}
      upgrade_version: ${{ matrix.upgrade_version }}
      archive_url: ${{ matrix.archive_url }}
      env_name: major-upgrade-stateful-workflow
    uses: ./.github/workflows/upgrade-gaia-v24-stateful-steps.yml

  # test-upgrade-release-testnet:
  #   needs: set-version-matrix
  #   strategy:
  #     matrix:
  #       ${{ fromJSON(needs.set-version-matrix.outputs.upgrade_versions) }}
  #     fail-fast: false
  #     #max-parallel: 3
  #   with:
  #     runs-on-os: cosmos-runner-set
  #     gaia_version: ${{ matrix.gaia_version }}
  #     upgrade_version: ${{ matrix.upgrade_version }}
  #     env_name: major-upgrade-theta-stateful-workflow
  #     archive_url: https://files.polypore.xyz/archived-state/theta-testnet/latest_v23.tar.gz
  #   uses: ./.github/workflows/upgrade-gaia-v24-stateful-steps.yml

  # test-upgrade-ics-testnet:
  #   needs: set-version-matrix
  #   strategy:
  #     matrix:
  #       ${{ fromJSON(needs.set-version-matrix.outputs.upgrade_versions) }}
  #     fail-fast: false
  #     #max-parallel: 3
  #   with:
  #     runs-on-os: cosmos-runner-set
  #     gaia_version: ${{ matrix.gaia_version }}
  #     upgrade_version: ${{ matrix.upgrade_version }}
  #     env_name: major-upgrade-ics-stateful-workflow
  #     archive_url: https://files.polypore.xyz/archived-state/ics-testnet-provider/latest_v23.tar.gz
  #   uses: ./.github/workflows/upgrade-gaia-v24-stateful-steps.yml
